import Head from 'next/head';
import styles from '../styles/Home.module.scss';
import Card from '../components/card';
import { StoreContext } from './_app.js';
import { useContext } from 'react';
import Search from '../components/search';

export async function getStaticProps() {
  const fetching = await fetch('https://pokeapi.co/api/v2/pokemon?limit=10');
  const json = await fetching.json();

  const pokeInfo = await Promise.all(
    json.results.map(async (item) => {
      const data = await fetch(item.url);
      const jsonData = await data.json();
      return await jsonData;
    })
  );

  return {
    props: { info: pokeInfo },
  };
}

export default function Home(props) {
  const { state, dispatch } = useContext(StoreContext);

  return (
    <div className="container">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Search />

      {state.Save.map((e, idx) => (
        <p key={idx}>{e.name}</p>
      ))}

      <section className={styles.section}>
        <h1>Pokedex</h1>
        <main>
          {props.info.map((item, idx) => (
            <Card key={idx} {...item} />
          ))}
        </main>
      </section>
    </div>
  );
}
